name: Build and Publish Plugins

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      CI: true  # tells Gradle not to run runMicrobot
      ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.NEXUS_USERNAME }}
      ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.NEXUS_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permissions
        run: |
          chmod +x gradlew
          chmod +x .github/scripts/parse_plugins_diff.py

      - name: Build JARs
        run: ./gradlew clean build

      - name: Configure Git for Actions
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Update plugin documentation
        run: |
          ./gradlew copyPluginDocs
          
          git add -f public/docs/ || true
          git reset public/docs/plugins.json 2>/dev/null || true
          
          if git diff --cached --quiet; then
            echo "✅ No changes to plugin documentation"
          else
            echo "📝 Plugin documentation updated"
          
            echo "Documentation files changed:"
            git diff --cached --name-only || true
          
            git commit -m "chore(ci): Update plugin documentation from GitHub Actions [skip ci]"
            git push
          fi

      - name: Update plugins.json
        run: |
          ./gradlew generatePluginsJson
          
          if git diff --quiet public/docs/plugins.json; then
            echo "✅ No changes to plugins.json"
          else
            echo "🔢 plugins.json updated from GitHub Actions build"
          
            echo "Changed plugins:"
            .github/scripts/parse_plugins_diff.py || echo "   (Unable to parse changes)"
          
            git add -f public/docs/plugins.json
            git commit -m "chore(ci): Update plugins.json from GitHub Actions [skip ci]"
            git push
          fi

      - name: Publish to Nexus
        run: ./gradlew publish

      - name: Create/Update GitHub Release with JARs
        uses: ncipollo/release-action@v1
        with:
          tag: latest-release
          name: Latest build
          body: "Commit: ${{ github.sha }}"
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "**/build/libs/*.jar"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          enable_jekyll: false
          allow_empty_commit: true